[build]
publish = ".next"
command = "npm run build"
functions = "functions/"

[build.environment]
#NETLIFY_NEXT_PLUGIN_SKIP = "true"
NODE_OPTIONS="–max-old-space-size=8192"

[dev]
framework = "#static"

#[[redirects]]
#from = "recoding-tech-v2.netlify.app"
#to = "techpolicy.press"

