[build]
publish = ".next"
command = "./stackbit-build.sh"
functions = "functions/"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
 from = "recoding-tech-v2.netlify.app"
 to = "recoding.tech"