[build]
publish = "out"
command = "./stackbit-build.sh"
functions = "functions/"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"

[dev]
framework = "#static"

[[redirects]]
from = "recoding-tech-v2.netlify.app"
to = "recoding.tech"

