name: Backup Routine
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  backup-dataset:
    runs-on: ubuntu-18.04
    name: Backup dataset
    defaults:
      run:
        working-directory: studio
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Export dataset
        run: |
          SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" \
          npx sanity dataset export \
          production backups/backup.tar.gz

      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: studio/backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
